# Generated by Django 5.1.3 on 2024-11-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_interview', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
